# Generated by Django 6.0.7 on 2026-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WARDEN', 'Warden'), ('STUDENT', 'Student'), ('ACCOUNTANT', 'accountant')], default='STUDENT', max_length=20),
        ),
    ]
