# Generated by Django 6.0.7 on 2026-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_capacity_room_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')]),
        ),
    ]
