# Generated by Django 6.0.7 on 2026-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_student_id_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
