# Generated by Django 6.0.7 on 2026-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('BIT', 'bit'), ('BSCSIT', 'bscsit'), ('BCA', 'bca'), ('BIM', 'bim'), ('BBS', 'bbs'), ('BBA', 'bba'), ('BBM', 'bbm'), ('BND', 'bnd')], default='BIT', max_length=10),
            preserve_default=False,
        ),
    ]
